# Generated by Django 3.1.1 on 2020-09-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form_with_upload',
            new_name='upload_model',
        ),
    ]
