# Generated by Django 3.1.1 on 2020-09-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0002_auto_20200920_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uploaded', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='upload_model',
            name='file_uploaded',
            field=models.FileField(upload_to='media/'),
        ),
    ]
