# Generated by Django 3.1.1 on 2020-10-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0003_auto_20200920_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload_doc',
        ),
        migrations.RemoveField(
            model_name='upload_model',
            name='file_name',
        ),
    ]
