# Generated by Django 3.1.1 on 2020-10-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0005_upload_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_model',
            name='file_name',
            field=models.CharField(default='file', max_length=500),
        ),
    ]
