# Generated by Django 3.1.1 on 2020-10-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0006_upload_model_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_model',
            name='file_name',
            field=models.CharField(max_length=500),
        ),
    ]
