# Generated by Django 3.1.1 on 2020-10-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0007_auto_20201005_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_model',
            name='user_folder',
            field=models.CharField(default=set, max_length=50),
            preserve_default=False,
        ),
    ]
