# Generated by Django 3.1.1 on 2020-10-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0009_auto_20201005_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_model',
            name='file_uploaded',
            field=models.FileField(upload_to='media/None'),
        ),
    ]
