# Generated by Django 3.1.1 on 2020-10-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0010_auto_20201005_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_model',
            name='file_uploaded',
            field=models.FileField(upload_to='media/'),
        ),
    ]
