# Generated by Django 3.1.1 on 2020-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_email',
            field=models.EmailField(default='none', max_length=254),
            preserve_default=False,
        ),
    ]
